### ISSUE TITLE
Create entity page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/manager.assets.ubuntu.com#18]
The entity page would be a page with details about the file with analytics of downloads for example.

**Comment by nottrobin** [comment]
I don't think this is especially needed for any specific reason, and the idea hasn't been mentioned again since 2015, and we certainly don't have any idea how it could be implemented.

If we do need to solve it, its solution would certainly live outside the *manager*, and almost certainly would be outside the server. It would instead be at the level of a transparent proxy frontend or something placed in front of the assets server.

I'm going to close this here now. If it turns out this is actually something we need to solve it will hopefully resurface, and then we can track it in the appropriate place.
